modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/ThreeTAG/PalladiumCore/issues"
license = "MIT License"

[[mods]]
modId = "palladiumcore"
version = "${version}"
displayName = "PalladiumCore"
authors = "Lucraft, Suff"
description = '''
Core mod to make multi-platform developing easier!
'''
logoFile = "palladiumcore_banner.png"
logoBlur = false

[modproperties.palladiumcore]
catalogueImageIcon = "palladiumcore_icon.png"

[[dependencies.palladiumcore]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.palladiumcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"